apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  namespace: {{ .Values.postgres.namespace }}
spec:
  volumeName: {{ .Release.Name }}-postgres-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi