apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.postgres.namespace }}

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres

  replicas: 1

  serviceName: {{ .Release.Name }}-postgres

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres

    spec:
      containers:
        - name: {{ .Release.Name }}-postgres
          image: postgres:15.3-alpine

          ports:
            - name: postgres
              containerPort: 5432

          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-postgres-configmap
                key: POSTGRES_DB

          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-postgres-configmap
                key: POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgres-secret
                key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              memory: {{ .Values.postgres.resources.requests.memory }}
              cpu: {{ .Values.postgres.resources.requests.cpu }}
            limits:
              memory: {{ .Values.postgres.resources.limits.memory }}
              cpu: {{ .Values.postgres.resources.limits.cpu }}

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $POSTGRES_USER
                - -d
                - $POSTGRES_DB
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc