export type Product = {
  id: number;
  title: string;
  asin: string;
  amazon_url: string;
  image_url: string | null;
  price: number;
  original_price: number | null;
  rating: number | null;
  reviews_count: number;
  category: string | null;
  description: string | null;
  age_group: string | null;
  gender_target: string | null;
  occasion: string | null;
  interests: string | null;
  recipient: string | null;
  is_available: boolean;
  created_at: string;
  updated_at: string;
};
