# Generated by Django 5.0.14 on 2026-09-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the Amazon product', max_length=255)),
                ('asin', models.CharField(db_index=True, help_text='Amazon Standard Identification Number', max_length=20, unique=True)),
                ('amazon_url', models.URLField(help_text='Direct link to the Amazon product page', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='Product main image link', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current listing price on Amazon', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Strikethrough price if on sale', max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating (e.g. 4.50)', max_digits=3, null=True)),
                ('reviews_count', models.IntegerField(default=0, help_text='Total number of customer reviews')),
                ('category', models.CharField(blank=True, db_index=True, help_text='e.g. Electronics, Home, Toys', max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, help_text='e.g. Kids, Teens, Adults', max_length=50, null=True)),
                ('gender_target', models.CharField(blank=True, help_text='e.g. Unisex, Men, Women', max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the item currently in stock?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
