# Generated by Django 5.0.14 on 2026-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='The name of the Amazon product')),
                ('asin', models.CharField(db_index=True, help_text='Amazon Standard Identification Number', max_length=20, unique=True)),
                ('amazon_url', models.TextField(help_text='Direct link to the Amazon product page')),
                ('image_url', models.TextField(blank=True, help_text='Product main image link', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current listing price on Amazon', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Strikethrough price if on sale', max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating (e.g. 4.50)', max_digits=3, null=True)),
                ('reviews_count', models.IntegerField(default=0, help_text='Total number of customer reviews')),
                ('category', models.CharField(blank=True, db_index=True, help_text='e.g. Electronics, Home, Toys', max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, help_text='e.g. Kids, Teens, Adults', max_length=50, null=True)),
                ('gender_target', models.CharField(blank=True, help_text='e.g. Unisex, Men, Women', max_length=50, null=True)),
                ('occasion', models.CharField(blank=True, help_text='e.g. Birthday, New Year, Anniversary', max_length=100, null=True)),
                ('interests', models.CharField(blank=True, help_text='e.g. Sports, Music, Gaming', max_length=255, null=True)),
                ('recipient', models.CharField(blank=True, help_text='e.g. Mom, Boyfriend, Colleague', max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is the item currently in stock?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Wishlist', help_text='Name of the gift list (e.g., Christmas Ideas)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, help_text='Presents saved to this list', related_name='in_wishlists', to='presents.present')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
