# Generated by Django 5.0.14 on 2026-10-06 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("presents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(help_text="The owner of this wishlist", on_delete=django.db.models.deletion.CASCADE, related_name="wishlists", to=settings.AUTH_USER_MODEL),
        ),
    ]
