# Generated by Django 5.0.14 on 2026-10-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="present",
            name="description",
            field=models.TextField(blank=True, help_text="Short description or features of the product", null=True),
        ),
    ]
