# Generated by Django 5.0.14 on 2026-10-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='amazon_url',
            field=models.TextField(help_text='Direct link to the Amazon product page'),
        ),
        migrations.AlterField(
            model_name='present',
            name='image_url',
            field=models.TextField(blank=True, help_text='Product main image link', null=True),
        ),
        migrations.AlterField(
            model_name='present',
            name='title',
            field=models.TextField(help_text='The name of the Amazon product'),
        ),
    ]
