namespace: gift-finder

frontend:
  deployment:
    replicas: 2
    label: frontend
    image: eug696/frontend:latest
    port: 3000
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"

backend:
  deployment:
    replicas: 2
    label: backend
    image: eug696/backend:latest
    port: 8000
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  config:
    DB_HOST: gift-finder-postgres.gf-postgres.svc.cluster.local
    DB_NAME: config
    DB_USER: postgres_user
    DB_PORT: 5432
    DB_PASSWORD: secure_dev_password_2026