apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}-frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.deployment.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.deployment.port }}
      targetPort: {{ .Values.frontend.deployment.port }}
  type: ClusterIP