apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-configmap
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: {{ .Values.backend.config.DB_HOST }}
  DB_NAME: {{ .Values.backend.config.DB_NAME }}
  DB_USER: {{ .Values.backend.config.DB_USER }}
  DB_PORT: {{ .Values.backend.config.DB_PORT | quote }}