apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-backend-secret
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    DB_PASSWORD: {{ .Values.backend.config.DB_PASSWORD | b64enc | quote }}