# Generated by Django 5.0.14 on 2026-10-07 06:44

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_users',
        ),
        migrations.CreateModel(
            name='UserVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=users.models.generate_numeric_code, max_length=6)),
                ('scenario', models.CharField(choices=[('password_reset', 'Password Reset'), ('email_confirmation', 'Email Confirmation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=users.models.get_expiry_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_verification_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
